# Generated by Django 4.1.1 on 2022-10-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
