# Generated by Django 4.1.1 on 2022-10-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_location_lat_alter_location_lng'),
        ('ads', '0003_ad_delete_ads_alter_category_options_ad_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='users.user'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.category'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
